# Generated by Django 4.0.4 on 2022-07-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0002_alter_student_signup_fname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_signup',
            name='fname',
            field=models.CharField(max_length=50),
        ),
    ]
